name: Neireez CI/CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to api.neireez.com
        uses: appleboy/ssh-action@master
        with:
          username: ali
          host: 217.21.78.152
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/api.neireez.com/
            ./scripts/deploy.sh
